name: Building the main application

on:
  push:
    branches: [ "main" ]
    paths:
    - Projects/BankManagementSystem/**
    - .github/workflows/**.yml
  pull_request:
    branches: [ "main" ]
    paths:
    - Projects/BankManagementSystem/**
    - .github/workflows/**.yml
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore "Projects/BankManagementSystem/BankManagementSystem.sln"
      
    - name: Building application on Debug mode
      run: dotnet build "Projects/BankManagementSystem/BankManagementSystem.sln" --no-restore --configuration Debug
      
    - name: Building application on Release mode
      run: dotnet build "Projects/BankManagementSystem/BankManagementSystem.sln" --no-restore --configuration Release