name: Building the main application

on:
  push:
    branches: [ "main" ]
    paths:
    - Projects/BankManagementSystem/**
    - .github/workflows/**.yml
  pull_request:
    branches: [ "main" ]
    paths:
    - Projects/BankManagementSystem/**
    - .github/workflows/**.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore "Projects/BankManagementSystem/BankManagementSystem.Server/BankManagementSystem.Server.csproj"
      
    - name: Build
      run: dotnet build "Projects/BankManagementSystem/BankManagementSystem.Server/BankManagementSystem.Server.csproj" --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test "Projects/BankManagementSystem/BankManagementSystem.Server.NUnit/BankManagementSystem.Server.NUnit.UnitTests.csproj" --logger "console;verbosity=detailed" --blame
